### ISSUE TITLE
Get to know about  more details of the projects under Season of Docs.

### ISSUE THREAD

**Issue by KaveeshBaddage** [arduino/season-of-docs#3]
I am Kaveesha Baddage. Currently, I am working as a Software Engineer and a technical writer. I have contributed and successfully completed an open source project in Google Summer of Code 2017. This time I am really interested to give my contribution on Season of Docs. 

I have experience on the Arduino platform and have written several articles about them. I checked the List of Ideas related to your organization under Season of Docs. And I am really interested to give my best contribution to them. Please inform me how can I communicate with mentors and get to know about the projects under Season of Docs.

Thanks.

**Comment by per1234** [comment]
Hello Kaveesha Baddage
Thanks for your interest in participating in Arduino's Season of Docs program!

My recommendation is that you decide on which project most appeals to you and matches your skill set. You can pick one from the [project ideas list](https://github.com/arduino/season-of-docs/blob/master/IDEAS.md) or come up with your own project idea.

Do some research on your project, including studying the information provided by the "Related material" links for your project on the project ideas list.

After that, contact us with any specific questions or proposals you have. We're happy to provide any information you need in order to produce a great project proposal in your technical writer application!

I also recommend that, if you haven't already done so, you read through Google's information about the Season of Docs program to make sure you understand the timeline and the various stages.
https://developers.google.com/season-of-docs/

You can communicate with us by emailing season-of-docs@arduino.cc. The mentors will see any email sent to that address.

Regards,
Per Tillisch
Arduino

**Comment by KaveeshBaddage** [comment]
Hi Tillisch,

Thank you for the information. I will select a project from the project idealist and will contact you through the given email if I need more information.
Thanks Again.

Regards,
Kaveesha

**Comment by KaveeshBaddage** [comment]
Hi @per1234 ,

I have sent an email to season-of-docs@arduino.cc regarding the  **Camera, Action! Project** several days ago. But I did not get any reply from your side. Please take a look at that and inform me how can I work on that project.

Thanks and regards,
Kaveesha

**Comment by per1234** [comment]
I'm very sorry for the delay responding to your email. We did receive your email but for some reason it didn't automatically open a ticket in our support tracker system. Please send the email again.

**Comment by KaveeshBaddage** [comment]
Hi @per1234,

I have sent the email again subjected as **Get started on "Camera, Action!" Project** . 

Thanks and regards,
Kaveesha
